schema_version: 1

context:
  version: "0.0.4"

package:
  name: esmvaltool-sample-data
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/ESMValTool_sample_data/esmvaltool_sample_data-${{ version }}.tar.gz
  sha256: ce8f18cd48e70db5b7e54d7b0d549b8f59a668f5a322b048eb60ee4bd0dc8d82

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip !=21.3
    - setuptools >=40.6.0
    - setuptools_scm >=6.2
  run:
    - python >=${{ python_min }}
    - iris >=3.6

tests:
  - python:
      imports:
        - esmvaltool_sample_data
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Sample climate data for ESMValTool.
  description: "ESMValTool_sample_data: data sample for ESMValTool."
  homepage: https://github.com/ESMValGroup/ESMValTool_sample_data
  repository: https://github.com/ESMValGroup/ESMValTool_sample_data
  documentation: https://github.com/ESMValGroup/ESMValTool_sample_data

extra:
  recipe-maintainers:
    - valeriupredoi
    - bouweandela
